backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "kurs"
    label: "Kurs"
    folder: "src/pages/kurs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "terapeut"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "terapeuter"
    label: "Terapeuter"
    folder: "src/pages/terapeuter"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "terapeut"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Tel", name: "tel", widget: "number"}
      - {label: "Email", name: "email", widget: "string"}
      - {label: "Workdays", name: "workdays", widget: "list", fields: [{label: Days, name: days, widget: string}, {label: Hours, name: hours, widget: string}]}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: whyImage, name: whyimage, widget: image}
          - {label: whyHeading, name: whyheading, widget: string}
          - {label: whySubheading, name: whysubheading, widget: string}
          - {label: whyText, name: whytext, widget: markdown}
          - {label: whoImage, name: whoimage, widget: image}
          - {label: whoHeading, name: whoheading, widget: string}
          - {label: whoSubheading, name: whosubheading, widget: string}
          - {label: whoText, name: whotext, widget: markdown}
      - file: "src/pages/eq-terapi/index.md"
        label: "EQ-Terapi Page"
        name: "eqtherapy"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "therapy-page"}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
          - {label: StepHeader, name: stepHeader, widget: string}
          - {label: StepTitle1, name: stepTitle1, widget: string}
          - {label: StepText1, name: stepText1, widget: text}
          - {label: StepTitle2, name: stepTitle2, widget: string}
          - {label: StepText2, name: stepText2, widget: text}
          - {label: StepTitle3, name: stepTitle3, widget: string}
          - {label: StepText3, name: stepText3, widget: text}
          - {label: StepTitle4, name: stepTitle4, widget: string}
          - {label: StepText4, name: stepText4, widget: text}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
      - file: "src/pages/kompetanse/index.md"
        label: "Kompetanse Page"
        name: "education"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "education-page"}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Subheading, name: subheading, widget: string}
      - file: "src/pages/contact/index.md"
        label: "Contact"
        name: "contact"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: QAs, name: qas, widget: list, fields: [{label: Question, name: question, widget: string}, {label: Answer, name: answer, widget: text}]}    
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/personvernerklaering/index.md"
        label: "Personvernerklaering"
        name: "personvernerklaering"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "personvernerklaering-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}